name: horizonground-docs

channels:
    - defaults
    - astropy

dependencies:
    - python=3.6
    - numpy
    - scipy
    - astropy    
    - mpi4py
    - runtests
    - pmesh
    - kdcount
    - mpsort
    - nbodykit    
    - sphinx
    - IPython
    - pip
    - pip:
        - nbsphinx
        - sphinx-issues
        - numpydoc
