name: horizonground-docs

channels:
    - bccp
    - conda-forge
    - defaults

dependencies:
    - python=3.6
    - numpy
    - scipy
    - astropy
    - nbodykit
    - pip
    - sphinx
    - IPython
    - numpydoc
    - nbsphinx
    
